import fs from "node:fs";

const API = process.env.FITLUNGE_CRM_QA_API || "http://localhost:5001/api";
const QA_DB = process.env.FITLUNGE_CRM_QA_DB || "fitlunge_crm_qa_20260815";
const ADMIN_EMAIL = process.env.FITLUNGE_CRM_QA_ADMIN || "crm.qa.admin@fitlunge.local";
const SALES_EMAIL = process.env.FITLUNGE_CRM_QA_SALES || "crm.qa.sales@fitlunge.local";
const PASSWORD = process.env.FITLUNGE_CRM_QA_PASSWORD || "FitLungeCRMQA2026";
const BACKEND_LOG = process.env.FITLUNGE_CRM_QA_BACKEND_LOG || "/tmp/fitlunge-crm-qa-backend.log";
let adminToken="", salesToken="", field=null, publicForm=null, clientForm=null, publicSubmission=null, client=null, passes=0;
function assert(condition,message){if(!condition)throw new Error(message)}
function row(name,status,detail=""){const dots=".".repeat(Math.max(2,48-name.length));console.log(`${name}${dots} ${status}${detail?`  ${detail}`:""}`)}
async function test(name,fn){try{const detail=await fn();passes++;row(name,"PASS",detail||"")}catch(error){row(name,"FAIL",error.message||String(error));throw error}}
async function request(path,{method="GET",token,body}={}){const headers={Accept:"application/json"};if(token)headers.Authorization=`Bearer ${token}`;if(body!==undefined)headers["Content-Type"]="application/json";const response=await fetch(`${API}${path}`,{method,headers,body:body===undefined?undefined:JSON.stringify(body)});const text=await response.text();let data=null;try{data=text?JSON.parse(text):null}catch{data={raw:text}}return{status:response.status,data}}
async function login(email){const res=await request("/auth/login",{method:"POST",body:{email,password:PASSWORD}});assert(res.status===200&&res.data?.token,`${email} login failed with HTTP ${res.status}`);return res.data.token}
async function main(){
 console.log("========================================");console.log("FITLUNGE FORM BUILDER AUTOMATED QA");console.log("ISOLATED QA DATABASE ONLY");console.log("========================================");console.log(`API: ${API}`);console.log(`QA DB: ${QA_DB}\n`);
 await test("00 Safety guard",async()=>{assert(API==="http://localhost:5001/api",`API must be localhost:5001, got ${API}`);assert(QA_DB.startsWith("fitlunge_crm_qa_"),`Unexpected QA database ${QA_DB}`);assert(fs.existsSync(BACKEND_LOG),"QA backend log is missing");const log=fs.readFileSync(BACKEND_LOG,"utf8");assert(log.includes(`CRM QA target database:\n${QA_DB}`),"Backend log does not confirm isolated QA database");const health=await request("/health");assert(health.status===200,`Health returned ${health.status}`);return"localhost:5001 + QA DB confirmed"});
 await test("01 Role logins",async()=>{[adminToken,salesToken]=await Promise.all([login(ADMIN_EMAIL),login(SALES_EMAIL)])});
 await test("02 Builder access ceiling",async()=>{const admin=await request("/forms",{token:adminToken});const sales=await request("/forms",{token:salesToken});assert(admin.status===200,`Admin forms expected 200, got ${admin.status}`);assert(sales.status===403,`Sales builder expected 403, got ${sales.status}`)});
 const suffix=`${Date.now()}-${Math.random().toString(36).slice(2,6)}`;
 await test("03 Create reusable form field",async()=>{const res=await request("/custom-fields/definitions",{method:"POST",token:adminToken,body:{label:`AUTO FORM Preferred time ${suffix}`,type:"text",entityTypes:["crm_contact","client"],required:false}});assert(res.status===201,`Custom field expected 201, got ${res.status}: ${res.data?.message||""}`);field=res.data.field;assert(field?._id,"Custom field id missing")});
 await test("04 Create public CRM form draft",async()=>{const res=await request("/forms",{method:"POST",token:adminToken,body:{name:`AUTO QA Enquiry ${suffix}`,slug:`auto-qa-enquiry-${suffix}`,visibility:"public",targetEntityType:"crm_contact",publicAction:"create_crm_lead",submitLabel:"Send enquiry",elements:[{kind:"heading",text:"Tell us about you"},{kind:"field",source:"standard",standardKey:"fullName",label:"Full name",required:true},{kind:"field",source:"standard",standardKey:"email",label:"Email",required:true},{kind:"field",source:"custom",customField:field._id,label:"Preferred time",required:false}]}});assert(res.status===201,`Create form expected 201, got ${res.status}: ${res.data?.message||""}`);publicForm=res.data.form;assert(publicForm?._id,"Form id missing")});
 await test("05 Draft hidden from public",async()=>{const res=await request(`/forms/public/${publicForm.slug}`);assert(res.status===404,`Draft public fetch expected 404, got ${res.status}`)});
 await test("06 Publish form",async()=>{const res=await request(`/forms/${publicForm._id}/status`,{method:"PATCH",token:adminToken,body:{status:"published"}});assert(res.status===200&&res.data.form?.status==="published",`Publish expected 200, got ${res.status}`);publicForm=res.data.form});
 await test("07 Public form retrieval",async()=>{const res=await request(`/forms/public/${publicForm.slug}`);assert(res.status===200,`Public fetch expected 200, got ${res.status}`);assert((res.data.form?.elements||[]).filter(e=>e.kind==="field").length===3,"Public form field count mismatch")});
 const name=`AUTO Form Lead ${suffix}`, email=`forms.${suffix}@example.com`;
 const fieldElements=publicForm.elements.filter(e=>e.kind==="field");
 const byStandard=Object.fromEntries(fieldElements.filter(e=>e.standardKey).map(e=>[e.standardKey,e]));
 const customElement=fieldElements.find(e=>e.source==="custom");
 await test("08 Public required validation",async()=>{const res=await request(`/forms/public/${publicForm.slug}/submit`,{method:"POST",body:{answers:{[byStandard.fullName._id]:name}}});assert(res.status===400,`Missing email expected 400, got ${res.status}`)});
 await test("09 Public submit -> CRM",async()=>{const res=await request(`/forms/public/${publicForm.slug}/submit`,{method:"POST",body:{answers:{[byStandard.fullName._id]:name,[byStandard.email._id]:email,[customElement._id]:"Evening"}}});assert(res.status===201,`Public submit expected 201, got ${res.status}: ${res.data?.message||""}`);publicSubmission=res.data;assert(publicSubmission?.submissionId,"Submission id missing")});
 let linkedSubmission=null;
 await test("10 Submission linked to CRM record",async()=>{const res=await request(`/forms/submissions?formId=${publicForm._id}`,{token:adminToken});assert(res.status===200,`Submission list expected 200, got ${res.status}`);linkedSubmission=(res.data.submissions||[]).find(s=>s._id===publicSubmission.submissionId);assert(linkedSubmission?.entityType==="crm_contact"&&linkedSubmission?.entityId,"Public response not linked to CRM")});
 await test("11 Custom value written to CRM",async()=>{const res=await request(`/custom-fields/records/crm_contact/${linkedSubmission.entityId}`,{token:salesToken});assert(res.status===200,`CRM custom values expected 200, got ${res.status}`);assert(res.data.values?.[field._id]==="Evening","Form custom value did not save to CRM")});
 await test("12 Duplicate submission reuses lead",async()=>{const res=await request(`/forms/public/${publicForm.slug}/submit`,{method:"POST",body:{answers:{[byStandard.fullName._id]:name,[byStandard.email._id]:email,[customElement._id]:"Morning"}}});assert(res.status===201,`Second public submit expected 201, got ${res.status}`);const list=await request(`/forms/submissions?formId=${publicForm._id}`,{token:adminToken});const latest=(list.data.submissions||[]).find(s=>s._id===res.data.submissionId);assert(String(latest?.entityId)===String(linkedSubmission.entityId),"Duplicate email created a different CRM contact")});
 await test("13 Create internal client form",async()=>{const res=await request("/forms",{method:"POST",token:adminToken,body:{name:`AUTO QA Client Form ${suffix}`,visibility:"internal",targetEntityType:"client",elements:[{kind:"field",source:"custom",customField:field._id,label:"Preferred time",required:true}]}});assert(res.status===201,`Client form create expected 201, got ${res.status}`);clientForm=res.data.form;const pub=await request(`/forms/${clientForm._id}/status`,{method:"PATCH",token:adminToken,body:{status:"published"}});assert(pub.status===200,"Client form publish failed");clientForm=pub.data.form});
 await test("14 Create QA client",async()=>{const res=await request("/clients",{method:"POST",token:adminToken,body:{fullName:`AUTO Form Client ${suffix}`,email:`formclient.${suffix}@example.com`,phone:`081${String(Date.now()).slice(-8)}`,program:"core"}});assert(res.status===201,`Client creation expected 201, got ${res.status}`);client=res.data.client;assert(client?._id,"Client id missing")});
 const clientElement=clientForm.elements.find(e=>e.kind==="field");
 await test("15 Internal form attaches to Client",async()=>{const res=await request(`/forms/${clientForm._id}/submit`,{method:"POST",token:adminToken,body:{entityType:"client",entityId:client._id,answers:{[clientElement._id]:"Afternoon"}}});assert(res.status===201,`Internal submit expected 201, got ${res.status}: ${res.data?.message||""}`);const values=await request(`/custom-fields/records/client/${client._id}`,{token:adminToken});assert(values.data.values?.[field._id]==="Afternoon","Internal form value did not attach to client")});
 await test("16 Sales cannot submit Client form",async()=>{const res=await request(`/forms/${clientForm._id}/submit`,{method:"POST",token:salesToken,body:{entityType:"client",entityId:client._id,answers:{[clientElement._id]:"Evening"}}});assert(res.status===403,`Sales client submission expected 403, got ${res.status}`)});
 await test("17 Available internal forms",async()=>{const res=await request("/forms/available/client",{token:adminToken});assert(res.status===200,`Available forms expected 200, got ${res.status}`);assert((res.data.forms||[]).some(f=>f._id===clientForm._id),"Published client form missing from available list")});
 await test("18 Form edit + preview data",async()=>{const res=await request(`/forms/${publicForm._id}`,{method:"PATCH",token:adminToken,body:{confirmationTitle:"We received it",submitLabel:"Continue"}});assert(res.status===200,`Form edit expected 200, got ${res.status}`);assert(res.data.form?.confirmationTitle==="We received it","Confirmation title did not update")});
 await test("19 Unpublish blocks new public submissions",async()=>{const off=await request(`/forms/${publicForm._id}/status`,{method:"PATCH",token:adminToken,body:{status:"draft"}});assert(off.status===200,"Unpublish failed");const fetch=await request(`/forms/public/${publicForm.slug}`);assert(fetch.status===404,`Unpublished form expected 404, got ${fetch.status}`)});
 await test("20 Form actions audited",async()=>{const res=await request("/audit",{token:adminToken});assert(res.status===200,`Audit expected 200, got ${res.status}`);const logs=res.data.logs||[];assert(logs.some(log=>String(log.entityId)===String(publicForm._id)&&String(log.action||"").toLowerCase().includes("form")),"Form audit entry not found")});
 console.log("\n========================================");console.log("FITLUNGE FORM BUILDER QA COMPLETE");console.log("========================================");console.log(`${passes}/21 PASSED`);console.log(`QA public form: ${publicForm._id}`);console.log(`QA client form: ${clientForm._id}`);console.log(`QA client: ${client._id}`);console.log("\nNo production API was contacted.");console.log("QA records were left in the isolated QA database for inspection.");
}
main().catch(error=>{console.error(`\nSTOP: ${error.message||error}`);process.exit(1)});
